FROM node:latest AS build
WORKDIR /app
COPY . .
RUN npm install
RUN npm install -g @angular/cli

FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/* /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
